# fly.toml app configuration file generated for bugtracker-jamiewillett on 2025-03-13T14:06:42Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bugtracker-staging-jamiewillett'
primary_region = 'lhr'

[build.args]
  NEXT_PUBLIC_API_URL = "https://bugtracker-backend-staging-jamiewillett.fly.dev"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
